# Generated by Django 2.1.4 on 2020-05-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclepasslog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepasslog',
            name='FPlate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='车牌号码'),
        ),
    ]
