# Generated by Django 2.1.4 on 2020-05-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclepasslog', '0002_auto_20200510_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclepasslog',
            options={'ordering': ['-CREATED_TIME']},
        ),
    ]
