# Generated by Django 2.1.4 on 2019-08-06 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materialsaccount',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPoundNo', models.CharField(blank=True, max_length=32, null=True, verbose_name='磅单编号')),
                ('FReceivetype', models.IntegerField(blank=True, default=0, null=True, verbose_name='收发类型')),
                ('F1stWeighTime', models.DateTimeField(blank=True, null=True, verbose_name='第一次称重时间')),
                ('F2ndWeighTime', models.DateTimeField(blank=True, null=True, verbose_name='第一次称重时间')),
                ('FWeighPerson', models.CharField(blank=True, max_length=32, null=True, verbose_name='过磅员')),
                ('FPoundsourceID', models.CharField(blank=True, max_length=32, null=True, verbose_name='单据来源')),
                ('FOperationalOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='业务发生单位')),
                ('FPlate', models.CharField(blank=True, max_length=32, null=True, verbose_name='车牌号码')),
                ('FWorktypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='业务类型')),
                ('FWarehouseID', models.CharField(blank=True, max_length=32, null=True, verbose_name='库房')),
                ('FUsesite', models.CharField(blank=True, max_length=32, null=True, verbose_name='使用部位')),
                ('FWaybillPicpath', models.ImageField(blank=True, default='', null=True, upload_to='material/', verbose_name='运单图片')),
                ('FInPicpath1', models.ImageField(blank=True, default='', null=True, upload_to='material/', verbose_name='进场图片1')),
                ('FInPicpath2', models.ImageField(blank=True, default='', null=True, upload_to='material/', verbose_name='进场图片2')),
                ('FOutPicpath1', models.ImageField(blank=True, default='', null=True, upload_to='material/', verbose_name='出场图片2')),
                ('FOutPicpath2', models.ImageField(blank=True, default='', null=True, upload_to='material/', verbose_name='出场图片2')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_MaterialsAccount',
            },
        ),
    ]
