# Generated by Django 2.1.4 on 2019-08-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receaccount', '0002_materaccountgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materaccountgoods',
            name='FPID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receaccount.materialsaccount'),
        ),
    ]
