# Generated by Django 2.1.4 on 2019-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receaccount', '0003_auto_20190806_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsaccount',
            name='FPoundsourceID',
            field=models.IntegerField(blank=True, choices=[(0, '称重'), (1, '补录'), (2, '移动验收')], null=True, verbose_name='单据来源'),
        ),
        migrations.AlterField(
            model_name='materialsaccount',
            name='FReceivetype',
            field=models.IntegerField(blank=True, choices=[(0, '收料'), (1, '发料')], null=True, verbose_name='收发类型'),
        ),
    ]
