# Generated by Django 2.1.4 on 2019-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receaccount', '0004_auto_20190806_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsaccount',
            name='F1stWeigh',
            field=models.FloatField(blank=True, null=True, verbose_name='第一次称重重量'),
        ),
        migrations.AddField(
            model_name='materialsaccount',
            name='F2ndWeigh',
            field=models.FloatField(blank=True, null=True, verbose_name='第二次称重重量'),
        ),
        migrations.AlterField(
            model_name='materialsaccount',
            name='F2ndWeighTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='第二次称重时间'),
        ),
    ]
