# Generated by Django 2.1.4 on 2019-08-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receaccount', '0005_auto_20190806_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialsaccount',
            name='FPoundsourceID',
        ),
        migrations.AddField(
            model_name='materialsaccount',
            name='FStatus',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '称重'), (1, '补录'), (2, '验收'), (3, '作废')], null=True, verbose_name='单据状态'),
        ),
    ]
