# Generated by Django 2.1.4 on 2019-08-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receaccount', '0006_auto_20190806_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsaccount',
            name='FWaybillDate',
            field=models.DateField(blank=True, null=True, verbose_name='单据日期'),
        ),
        migrations.AddField(
            model_name='materialsaccount',
            name='FWaybillNo',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='原始运单号'),
        ),
        migrations.AlterField(
            model_name='materialsaccount',
            name='FStatus',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '称重'), (1, '补录'), (2, '验收'), (3, '作废'), (4, '退回')], null=True, verbose_name='单据状态'),
        ),
    ]
