# Generated by Django 2.1.4 on 2019-08-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receaccount', '0007_auto_20190806_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materaccountgoods',
            name='FMaterID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materials'),
        ),
    ]
