# Generated by Django 2.1.4 on 2019-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receaccount', '0008_auto_20190807_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsaccount',
            name='FStatus',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '称重'), (1, '补录'), (2, '验收'), (3, '作废'), (4, '退回'), (5, '异常验收')], null=True, verbose_name='单据状态'),
        ),
    ]
