# Generated by Django 2.1.4 on 2019-07-30 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='envrule',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FRule', models.CharField(blank=True, max_length=32, null=True, verbose_name='规则名称')),
                ('FDevID', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备ID')),
                ('FAreaID', models.CharField(blank=True, max_length=32, null=True, verbose_name='区域ID')),
                ('FNodename', models.CharField(blank=True, max_length=32, null=True, verbose_name='节点名称')),
                ('FMonitoritem', models.CharField(blank=True, max_length=32, null=True, verbose_name='监测项目')),
                ('FMonitorvalue', models.CharField(blank=True, max_length=32, null=True, verbose_name='监测值')),
                ('FMonitorcondition', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '等于'), (1, '大于'), (2, '小于'), (3, '大于等于'), (4, '小于等于'), (5, '不等于')], null=True, verbose_name='监测条件')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_EnvRule',
            },
        ),
    ]
