# Generated by Django 2.1.4 on 2019-07-31 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envrule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='envruleswitch',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPID', models.CharField(blank=True, max_length=32, null=True, verbose_name='FPID')),
                ('FPort', models.IntegerField(blank=True, null=True, verbose_name='继电器端口号')),
                ('FStatus', models.BooleanField(default=True, verbose_name='继电器状态')),
                ('FCommand', models.CharField(blank=True, max_length=32, null=True, verbose_name='规则名称')),
                ('FDriverdevice', models.CharField(blank=True, max_length=32, null=True, verbose_name='规则名称')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_EnvRuleSwitch',
            },
        ),
    ]
