# Generated by Django 2.1.4 on 2019-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envrule', '0002_envruleswitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envruleswitch',
            name='FCommand',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='继电器指令'),
        ),
        migrations.AlterField(
            model_name='envruleswitch',
            name='FDriverdevice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='控制外设'),
        ),
    ]
