# Generated by Django 2.1.4 on 2019-07-16 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FName', models.CharField(blank=True, max_length=32, null=True, verbose_name='人员姓名')),
                ('FType', models.IntegerField(choices=[(0, '管理人员'), (1, '班组长'), (2, '员工')], default=2, verbose_name='员工类型')),
                ('FWorktypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属工种')),
                ('FGroupID', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属班组')),
                ('FTeamID', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属施工队')),
                ('FIsSafetrain', models.BooleanField(default=True, verbose_name='是否进行安全培训')),
                ('FSpecialequ', models.BooleanField(default=True, verbose_name='是否操作特种设备')),
                ('FSafetrainDate', models.DateTimeField(blank=True, null=True, verbose_name='培训时间')),
                ('FSafetrainHour', models.IntegerField(blank=True, null=True, verbose_name='培训课时')),
                ('FEntranceannex', models.ImageField(blank=True, null=True, upload_to='hrpic/', verbose_name='进场附件')),
                ('FIDcard', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('FIDcardbeginDate', models.DateTimeField(blank=True, null=True, verbose_name='身份证有效起始日期')),
                ('FIDcardendDate', models.DateTimeField(blank=True, null=True, verbose_name='身份证有效结束日期')),
                ('FIDcardIsIndefinite', models.BooleanField(default=True, verbose_name='身份证产期有效')),
                ('FSex', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('FNation', models.CharField(blank=True, max_length=32, null=True, verbose_name='民族')),
                ('FBirthday', models.DateTimeField(blank=True, null=True, verbose_name='出生日期')),
                ('FNaviveplace', models.CharField(blank=True, max_length=32, null=True, verbose_name='籍贯')),
                ('FHomeaddress', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭住址')),
                ('FSignorg', models.CharField(blank=True, max_length=32, null=True, verbose_name='签发机关')),
                ('FTel', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系方式')),
                ('FPolitident', models.CharField(blank=True, max_length=32, null=True, verbose_name='政治面貌')),
                ('FSpeciality', models.CharField(blank=True, max_length=32, null=True, verbose_name='特长')),
                ('FMarital', models.IntegerField(blank=True, choices=[(0, '未婚'), (1, '已婚'), (2, '离异')], null=True, verbose_name='婚姻状况')),
                ('FLevelofedu', models.CharField(blank=True, max_length=32, null=True, verbose_name='文化程度')),
                ('FTempaddress', models.CharField(blank=True, max_length=32, null=True, verbose_name='暂住地址')),
                ('FBank', models.CharField(blank=True, max_length=32, null=True, verbose_name='开户银行')),
                ('FBankaccount', models.CharField(blank=True, max_length=32, null=True, verbose_name='银行账号')),
                ('FEmercontact', models.CharField(blank=True, max_length=32, null=True, verbose_name='紧急联系人')),
                ('FEmercontacttel', models.CharField(blank=True, max_length=32, null=True, verbose_name='紧急联系人电话')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_Personnel',
            },
        ),
    ]
