# Generated by Django 2.1.4 on 2019-07-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='FContractState',
            field=models.IntegerField(blank=True, choices=[(0, '未签合同'), (1, '已签合同')], null=True, verbose_name='合同状态'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='FPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='hrpic/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='FQuitDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退场日期'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FStatus',
            field=models.IntegerField(choices=[(0, '登记'), (1, '退场'), (2, '禁用')], default=0, verbose_name='状态'),
        ),
    ]
