# Generated by Django 2.1.4 on 2019-07-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20190716_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='FBirthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FContractState',
            field=models.BooleanField(default=True, verbose_name='劳动合同'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FIDcardbeginDate',
            field=models.DateField(blank=True, null=True, verbose_name='身份证有效起始日期'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FIDcardendDate',
            field=models.DateField(blank=True, null=True, verbose_name='身份证有效结束日期'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FMarital',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '未婚'), (1, '已婚'), (2, '离异')], null=True, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FSex',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FStatus',
            field=models.IntegerField(choices=[(None, '请选择数据'), (0, '登记'), (1, '退场'), (2, '禁用')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FType',
            field=models.IntegerField(choices=[(None, '请选择数据'), (0, '管理人员'), (1, '班组长'), (2, '员工')], default=2, verbose_name='员工类型'),
        ),
    ]
