# Generated by Django 2.1.4 on 2019-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20190717_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='FIDcardIsIndefinite',
            field=models.BooleanField(default=False, verbose_name='身份证长期有效'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FQuitDate',
            field=models.DateField(blank=True, null=True, verbose_name='退场日期'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FSpecialequ',
            field=models.BooleanField(default=False, verbose_name='是否操作特种设备'),
        ),
    ]
