# Generated by Django 2.1.4 on 2019-07-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_auto_20190717_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='FQuitDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退场日期'),
        ),
    ]
