# Generated by Django 2.1.4 on 2019-07-18 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_auto_20190717_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='personcertif',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPID', models.CharField(blank=True, max_length=32, null=True)),
                ('FCertitypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='证书类别')),
                ('FSkilllevel', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '初级'), (1, '中级'), (2, '高级'), (3, '特种工')], null=True, verbose_name='技能等级')),
                ('FCertificateNo', models.CharField(blank=True, max_length=32, null=True, verbose_name='证书编号')),
                ('FIssueOrg', models.CharField(blank=True, max_length=32, null=True, verbose_name='签发机关')),
                ('FIssueDate', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('FLimitDate', models.DateField(blank=True, null=True, verbose_name='有效日期')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('FCertiFilepath', models.ImageField(blank=True, default='', null=True, upload_to='certificate/', verbose_name='证书')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_PersonnelCertificate',
            },
        ),
    ]
