# Generated by Django 2.1.4 on 2019-07-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_personcertif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcertif',
            name='FCertificateNo',
            field=models.CharField(max_length=32, verbose_name='证书编号'),
        ),
        migrations.AlterField(
            model_name='personcertif',
            name='FCertitypeID',
            field=models.CharField(max_length=32, verbose_name='证书类别'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FEntranceannex',
            field=models.ImageField(blank=True, null=True, upload_to='safetrain/', verbose_name='进场附件'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FIsSafetrain',
            field=models.BooleanField(default=False, verbose_name='是否进行安全培训'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FSafetrainDate',
            field=models.DateField(blank=True, null=True, verbose_name='培训时间'),
        ),
    ]
