# Generated by Django 2.2 on 2019-12-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_auto_20190718_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='FWoTuGUID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='沃土平台GUID'),
        ),
    ]
