# Generated by Django 2.2 on 2019-12-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_personnel_fwotuguid'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='FWoTuFaceGUID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='沃土平台人脸GUID'),
        ),
    ]
