# Generated by Django 2.1.4 on 2020-01-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_personnel_fwotufaceguid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['FType', 'FWorktypeID']},
        ),
    ]
