# Generated by Django 2.1.4 on 2020-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_auto_20200101_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='FWoTuFaceGUID',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='沃土平台人脸GUID'),
        ),
    ]
