# Generated by Django 2.1.4 on 2019-08-01 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiclefiles',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPlate', models.CharField(blank=True, max_length=32, null=True, verbose_name='车牌号码')),
                ('FDrivers', models.CharField(blank=True, max_length=32, null=True, verbose_name='驾驶人')),
                ('FOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属单位')),
                ('FVehicletypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='车辆类型')),
                ('FValiddate', models.DateField(blank=True, null=True, verbose_name='有效日期')),
                ('FMaterielID', models.CharField(blank=True, max_length=32, null=True, verbose_name='运输物料')),
                ('FRfidcard', models.CharField(blank=True, max_length=32, null=True, verbose_name='RFID卡号')),
                ('FDevID', models.CharField(blank=True, max_length=32, null=True, verbose_name='GPS设备ID')),
                ('FIsMonitor', models.BooleanField(default=False, verbose_name='是否电子围栏监控')),
                ('FTare', models.FloatField(blank=True, null=True, verbose_name='车辆皮重')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_VehicleFiles',
            },
        ),
    ]
