# Generated by Django 2.1.4 on 2019-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclefiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclefiles',
            name='FPlate',
            field=models.CharField(default='None', max_length=32, unique=True, verbose_name='车牌号码'),
        ),
    ]
