# Generated by Django 2.1.4 on 2019-08-13 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menchanical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mecoperauth',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FMecserialID', models.CharField(blank=True, max_length=32, null=True, verbose_name='机械ID')),
                ('FAuthpersonID', models.CharField(blank=True, max_length=32, null=True, verbose_name='授权操作人员ID')),
                ('FAuthTimeslot', models.CharField(blank=True, max_length=32, null=True, verbose_name='授权操作时间段')),
                ('FAuthDeadline', models.CharField(blank=True, max_length=32, null=True, verbose_name='截止日期')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_MecOperAuth',
            },
        ),
    ]
