# Generated by Django 2.1.4 on 2019-08-13 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menchanical', '0003_auto_20190813_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='mecoperlog',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FMecserialFID', models.CharField(blank=True, max_length=32, null=True)),
                ('FPersonID', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作人员')),
                ('FOperbeh', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '上班'), (1, '下班')], null=True, verbose_name='操作行为')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_MecOperLog',
            },
        ),
    ]
