# Generated by Django 2.1.4 on 2019-07-21 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devinterface',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FName', models.CharField(blank=True, max_length=32, null=True, verbose_name='接口名称')),
                ('FInterfaceTypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='接口方式')),
                ('FTransmode', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '实时'), (1, '间隔')], null=True, verbose_name='传输方式')),
                ('FInterval', models.IntegerField(blank=True, null=True, verbose_name='间隔时间')),
                ('FAddress', models.CharField(blank=True, max_length=32, null=True, verbose_name='访问地址')),
                ('FDevID', models.CharField(blank=True, max_length=32, null=True, verbose_name='绑定设备')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_DevInterface',
            },
        ),
    ]
