# Generated by Django 2.1.4 on 2019-07-21 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0002_devinterface_fport'),
    ]

    operations = [
        migrations.CreateModel(
            name='interfaceparam',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPID', models.CharField(blank=True, max_length=32, null=True)),
                ('FParam', models.CharField(blank=True, max_length=32, null=True, verbose_name='参数名称')),
                ('FValue', models.CharField(blank=True, max_length=128, null=True, verbose_name='参数值')),
                ('FTypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='参数类型')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_InterfaceParam',
            },
        ),
    ]
