# Generated by Django 2.1.4 on 2019-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0003_interfaceparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinterface',
            name='FRequestType',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'DELETE')], null=True, verbose_name='接口类型'),
        ),
    ]
