# Generated by Django 2.1.4 on 2019-08-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0004_devinterface_frequesttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinterface',
            name='FAddress',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='访问地址'),
        ),
    ]
