# Generated by Django 2.1.4 on 2019-09-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0005_auto_20190821_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devinterface',
            options={'ordering': ['FDevID']},
        ),
    ]
