# Generated by Django 2.1.4 on 2019-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0006_auto_20190911_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinterface',
            name='FInterfaceExtID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='扩展分类'),
        ),
    ]
