# Generated by Django 2.2 on 2019-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0008_interfaceparam_fsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceparam',
            name='FPosition',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='参数位置'),
        ),
    ]
