# Generated by Django 2.2 on 2019-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0009_interfaceparam_fposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceparam',
            name='FPosition',
            field=models.IntegerField(blank=True, choices=[(0, 'BODY'), (1, 'HEADER')], default=0, null=True, verbose_name='参数位置'),
        ),
    ]
