# Generated by Django 2.1.4 on 2019-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0010_auto_20191017_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceparam',
            name='FPosition',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, 'BODY'), (1, 'HEADER')], default=0, null=True, verbose_name='参数位置'),
        ),
    ]
