# Generated by Django 2.1.4 on 2019-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0012_auto_20191125_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinterface',
            name='FTransmode',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '实时'), (1, '间隔'), (2, '单次')], null=True, verbose_name='传输方式'),
        ),
    ]
