# Generated by Django 2.1.4 on 2019-11-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0013_auto_20191126_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinterface',
            name='FSrvPID',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='服务文件PID'),
        ),
    ]
