# Generated by Django 2.2 on 2019-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0014_devinterface_fsrvpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinterface',
            name='FSrvFile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='服务文件'),
        ),
    ]
