# Generated by Django 2.2 on 2019-12-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0015_auto_20191210_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinterface',
            name='FAppFID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='调用AppID'),
        ),
    ]
