# Generated by Django 2.1.4 on 2020-01-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0018_auto_20191221_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceparam',
            name='FValue',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='参数值'),
        ),
    ]
