# Generated by Django 2.1.4 on 2020-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterface', '0019_auto_20200115_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinterface',
            name='FInterfaceAttribID',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '接口'), (1, '服务'), (2, '服务组')], null=True, verbose_name='接口属性'),
        ),
    ]
