# Generated by Django 2.1.4 on 2019-07-08 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('FPID', models.CharField(blank=True, max_length=32, null=True)),
                ('FBaseID', models.CharField(blank=True, max_length=32, null=True, verbose_name='字典编号')),
                ('FBase', models.CharField(blank=True, max_length=32, null=True, verbose_name='字典名称')),
                ('FDesc', models.CharField(blank=True, max_length=128, null=True, verbose_name='字典描述')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_Base',
            },
        ),
    ]
