# Generated by Django 2.1.4 on 2020-03-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0003_auto_20190710_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='FMappingCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='映射外部系统编码'),
        ),
    ]
