# Generated by Django 2.1.4 on 2019-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mencrepairlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mencrepairlog',
            name='FHappendate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='故障发生时间'),
        ),
    ]
