# Generated by Django 2.1.4 on 2019-08-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnpound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnpound',
            name='FResultDate',
            field=models.DateField(blank=True, null=True, verbose_name='处理时间'),
        ),
    ]
