# Generated by Django 2.1.4 on 2019-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FPrefix', models.CharField(blank=True, max_length=32, null=True, verbose_name='前缀')),
                ('FDate', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('FSequence', models.IntegerField(blank=True, null=True, verbose_name='顺序号')),
            ],
            options={
                'db_table': 'T_Sequence',
            },
        ),
    ]
