# Generated by Django 2.1.4 on 2019-07-14 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属分包商')),
                ('FName', models.CharField(blank=True, max_length=32, null=True, verbose_name='施工队名称')),
                ('FTeammgr', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目经理')),
                ('FMgrtel', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('FIDcard', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('FFirstDate', models.DateField(blank=True, null=True, verbose_name='合同签订日期')),
                ('FScope', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系电话')),
                ('FAmount', models.FloatField(blank=True, null=True, verbose_name='承包金额')),
                ('FEvaluate', models.IntegerField(choices=[(0, '合格'), (1, '不合格')], default=0, verbose_name='评价')),
                ('FScale', models.IntegerField(blank=True, null=True, verbose_name='队伍规模')),
                ('FSource', models.CharField(blank=True, max_length=32, null=True, verbose_name='队伍来源')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_Team',
            },
        ),
    ]
