# Generated by Django 2.1.4 on 2019-07-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='FIDcard',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='team',
            name='FScope',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='承包范围'),
        ),
    ]
