# Generated by Django 2.2 on 2019-07-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organize',
            name='FOrgID',
            field=models.CharField(blank=True, error_messages={'unique': '信用代码重复'}, max_length=32, null=True, unique=True, verbose_name='统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='organize',
            name='FScope',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='经营范围'),
        ),
    ]
