# Generated by Django 2.2 on 2019-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0002_auto_20190710_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organize',
            name='FOrgID',
            field=models.CharField(error_messages={'unique': '信用代码重复'}, max_length=32, unique=True, verbose_name='统一社会信用代码'),
        ),
    ]
