# Generated by Django 2.2 on 2019-07-10 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0003_auto_20190710_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organize',
            name='FID',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organize',
            name='FOrgname',
            field=models.CharField(error_messages={'unique': '组织名称重复'}, max_length=32, unique=True, verbose_name='组织名称'),
        ),
    ]
