# Generated by Django 2.2 on 2019-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0005_orgqualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgqualifications',
            name='FFilepath',
            field=models.ImageField(blank=True, null=True, upload_to='orgqualpic/'),
        ),
        migrations.AlterField(
            model_name='orgqualifications',
            name='FQualification',
            field=models.CharField(max_length=32, verbose_name='资质名称'),
        ),
    ]
