# Generated by Django 2.1.4 on 2020-03-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0006_auto_20190712_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='organize',
            name='FCorpType',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='企业性质'),
        ),
        migrations.AddField(
            model_name='organize',
            name='FLicenseNum',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工商营业执照注册号'),
        ),
    ]
