# Generated by Django 2.1.4 on 2019-08-04 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materials',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FMaterID', models.CharField(blank=True, max_length=32, null=True, verbose_name='物料编码')),
                ('FName', models.CharField(blank=True, max_length=32, null=True, verbose_name='物料名称')),
                ('FGoodsTypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='物料类型编号')),
                ('FUnitID', models.CharField(blank=True, max_length=32, null=True, verbose_name='计量单位')),
                ('FSpec', models.CharField(blank=True, max_length=32, null=True, verbose_name='计量单位')),
                ('FTexture', models.CharField(blank=True, max_length=32, null=True, verbose_name='材质')),
                ('FPositiveDeviation', models.FloatField(blank=True, null=True, verbose_name='正偏差')),
                ('FNegativeDeviation', models.FloatField(blank=True, null=True, verbose_name='负偏差')),
                ('FRFID', models.CharField(blank=True, max_length=32, null=True, verbose_name='RFID')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_Materials',
            },
        ),
    ]
