# Generated by Django 2.1.4 on 2020-03-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20190804_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='FStatus',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
