# Generated by Django 2.1.4 on 2020-01-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['FTeamID', 'CREATED_TIME']},
        ),
    ]
