# Generated by Django 2.1.4 on 2019-08-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_unit_fstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['FUnitgroupID', '-FIsBaseunit', 'FUnit']},
        ),
    ]
