# Generated by Django 2.1.4 on 2019-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedpassage',
            name='FDesc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
    ]
