# Generated by Django 2.1.4 on 2019-07-22 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0002_pedpassage_fdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='passagerecord',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPersonID', models.CharField(blank=True, max_length=32, null=True, verbose_name='人员ID')),
                ('FPassageID', models.CharField(blank=True, max_length=32, null=True, verbose_name='人行通道ID')),
                ('FAuthtypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='通行授权方式')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_PassageRecord',
            },
        ),
    ]
