# Generated by Django 2.1.4 on 2019-07-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0004_auto_20190723_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagerecord',
            name='FPersonID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel', verbose_name='人员ID'),
        ),
    ]
