# Generated by Django 2.1.4 on 2019-07-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0005_auto_20190723_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagerecord',
            name='FPassageID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedpassage.pedpassage', verbose_name='人行通道ID'),
        ),
    ]
