# Generated by Django 2.2 on 2019-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0006_auto_20190723_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedpassage',
            name='FInitStatus',
            field=models.BooleanField(default=False, verbose_name='初始化状态'),
        ),
    ]
