# Generated by Django 2.2 on 2020-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0007_pedpassage_finitstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagerecord',
            name='FTemperature',
            field=models.FloatField(blank=True, null=True, verbose_name='体温'),
        ),
    ]
