# Generated by Django 2.1.4 on 2020-03-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0008_passagerecord_ftemperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passagerecord',
            options={'ordering': ['-CREATED_TIME']},
        ),
    ]
