# Generated by Django 2.1.4 on 2020-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedpassage', '0010_auto_20200513_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagerecord',
            name='FPersonGUID',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='人员原始GUID'),
        ),
    ]
