# Generated by Django 2.1.4 on 2019-07-03 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('FUserID', models.CharField(max_length=32, verbose_name='用户账户')),
                ('FUserpwd', models.CharField(max_length=32, verbose_name='用户密码')),
                ('FType', models.IntegerField(choices=[(0, '企业账户'), (1, '合作伙伴'), (3, '管理员')], default=0, verbose_name='用户类型')),
                ('FStatus', models.IntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='状态')),
                ('FUsername', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名称')),
                ('FOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属组织')),
                ('FRoleID', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色')),
                ('FTel', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_User',
            },
        ),
    ]
