# Generated by Django 2.1.4 on 2019-07-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FStatus',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
