# Generated by Django 2.1.4 on 2019-07-09 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190704_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FID',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='FType',
            field=models.IntegerField(choices=[(0, '企业账户'), (1, '合作伙伴'), (2, '管理员')], default=0, verbose_name='用户类型'),
        ),
    ]
