# Generated by Django 2.1.4 on 2020-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190709_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FType',
            field=models.IntegerField(choices=[(0, '企业账户'), (1, '合作伙伴'), (2, '管理员'), (3, '政务平台')], default=0, verbose_name='用户类型'),
        ),
    ]
