# Generated by Django 2.1.4 on 2019-08-19 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitordev',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FChannel', models.CharField(blank=True, max_length=32, null=True, verbose_name='通道名称')),
                ('FIPAddress', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', verbose_name='设备IP地址')),
                ('FAccessuser', models.CharField(blank=True, max_length=32, null=True, verbose_name='接入用户名')),
                ('FAccesspwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='接入密码')),
                ('FDevtype', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '枪机'), (1, '球机')], null=True, verbose_name='设备类型')),
                ('FIsYuntai', models.BooleanField(default=False, verbose_name='是否云台控制')),
                ('FChannelNo', models.CharField(blank=True, max_length=32, null=True, verbose_name='通道号')),
                ('FPort', models.IntegerField(blank=True, null=True, verbose_name='端口号')),
                ('FProtocoltype', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, 'RTSP'), (1, 'ONVIF')], null=True, verbose_name='接入协议')),
                ('FProtocol', models.CharField(blank=True, max_length=32, null=True, verbose_name='协议地址')),
                ('FAreaID', models.CharField(blank=True, max_length=32, null=True, verbose_name='安装区域')),
                ('FTransmode', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, 'TCP'), (1, 'UDP')], null=True, verbose_name='传输方式')),
                ('FIsOpenAudio', models.BooleanField(default=True, verbose_name='开启音频')),
                ('FIsOpenVideo', models.BooleanField(default=True, verbose_name='开启视频')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_MonitorDev',
            },
        ),
    ]
