# Generated by Django 2.1.4 on 2020-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitordev', '0002_auto_20190819_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordev',
            name='FDevID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='设备唯一编码'),
        ),
    ]
