# Generated by Django 2.1.4 on 2019-07-31 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclegate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiclesigin',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPID', models.CharField(blank=True, max_length=32, null=True, verbose_name='FPID')),
                ('FVehtypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='车辆类型')),
                ('FIsCurrent', models.BooleanField(default=True, verbose_name='通行策略')),
                ('FBegindate', models.DateField(blank=True, null=True, verbose_name='起始时间')),
                ('FEnddate', models.DateField(blank=True, null=True, verbose_name='截止时间')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_VehicleSigin',
            },
        ),
    ]
