# Generated by Django 2.1.4 on 2019-07-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclegate', '0002_vehiclesigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesigin',
            name='FIsIndefinite',
            field=models.BooleanField(default=False, verbose_name='长期有效'),
        ),
    ]
