# Generated by Django 2.1.4 on 2020-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclegate', '0003_vehiclesigin_fisindefinite'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesigin',
            name='FStatus',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
