# Generated by Django 2.1.4 on 2019-12-09 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prjcheck',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPrjID', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目编号')),
                ('FAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='事件地址')),
                ('FProblem', models.CharField(blank=True, max_length=100, null=True, verbose_name='问题名称')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='事件描述')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_PrjCheck',
            },
        ),
    ]
