# Generated by Django 2.1.4 on 2019-12-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prjcheck',
            name='FPic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='itemcheckpic/', verbose_name='检查图片'),
        ),
    ]
