# Generated by Django 2.1.4 on 2019-07-19 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FDevID', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备编号')),
                ('FDevice', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备名称')),
                ('FDevtypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备类型')),
                ('FDevIP', models.GenericIPAddressField(blank=True, null=True, verbose_name='设备IP')),
                ('FPort', models.IntegerField(blank=True, null=True, verbose_name='设备端口号')),
                ('FManufacturer', models.IntegerField(blank=True, null=True, verbose_name='设备厂商')),
                ('FBrand', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备品牌')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_Device',
            },
        ),
    ]
