# Generated by Django 2.1.4 on 2019-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='FMainstaff',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='维护人员'),
        ),
        migrations.AddField(
            model_name='device',
            name='FMainstafftel',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='device',
            name='FWarrantyDate',
            field=models.DateField(blank=True, null=True, verbose_name='质保期'),
        ),
    ]
