# Generated by Django 2.1.4 on 2019-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20190720_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='FLat',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='device',
            name='FLong',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='device',
            name='FPosition',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='摆放位置'),
        ),
    ]
