# Generated by Django 2.1.4 on 2019-08-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20190722_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='FManufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备厂商'),
        ),
    ]
