# Generated by Django 2.1.4 on 2019-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20190820_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['FDevtypeID']},
        ),
        migrations.AddField(
            model_name='device',
            name='FInterfacePos',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='接口定位'),
        ),
    ]
