# Generated by Django 2.1.4 on 2019-11-21 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20190927_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='devcallinterface',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPID', models.CharField(blank=True, max_length=32, null=True)),
                ('FCallSigCode', models.CharField(blank=True, max_length=32, null=True, verbose_name='调用特征码')),
                ('FInterfaceID', models.CharField(blank=True, max_length=32, null=True, verbose_name='接口FID')),
                ('FDataMode', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '仅调用'), (1, '数据存储')], default=0, null=True, verbose_name='数据模式')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_DevCallInterface',
            },
        ),
    ]
