# Generated by Django 2.1.4 on 2019-11-25 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elevatorinterfacesrv',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FElevatorID', models.CharField(blank=True, max_length=32, null=True, verbose_name='电梯设备FID')),
                ('hoist_box_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='黑匣子编号')),
                ('cage_id', models.IntegerField(blank=True, null=True, verbose_name='吊笼编号')),
                ('door_lock_state', models.IntegerField(blank=True, null=True, verbose_name='门锁状态')),
                ('driver_identification_state', models.IntegerField(blank=True, null=True, verbose_name='身份认证状态')),
                ('height_percentage', models.FloatField(blank=True, null=True, verbose_name='高度百分比')),
                ('hoist_system_state', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统状态')),
                ('hoist_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='时间戳')),
                ('real_time_gradient1', models.FloatField(blank=True, null=True, verbose_name='实时倾斜度1')),
                ('real_time_gradient2', models.FloatField(blank=True, null=True, verbose_name='实时倾斜度2')),
                ('real_time_height', models.FloatField(blank=True, null=True, verbose_name='实时高度')),
                ('real_time_lifting_weight', models.FloatField(blank=True, null=True, verbose_name='实时起重量')),
                ('real_time_number_of_people', models.IntegerField(blank=True, null=True, verbose_name='实时人数')),
                ('real_time_or_alarm', models.IntegerField(blank=True, null=True, verbose_name='结果返回类型')),
                ('real_time_speed', models.FloatField(blank=True, null=True, verbose_name='实时速度')),
                ('real_time_speed_direction', models.IntegerField(blank=True, null=True, verbose_name='运行方向')),
                ('tilt_percentage1', models.FloatField(blank=True, null=True, verbose_name='倾斜百分比1')),
                ('tilt_percentage2', models.FloatField(blank=True, null=True, verbose_name='倾斜百分比2')),
                ('weight_percentage', models.FloatField(blank=True, null=True, verbose_name='重量百分比')),
                ('system_state', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统状态')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='加工速度')),
                ('elevator_manager', models.CharField(blank=True, max_length=32, null=True, verbose_name='安全员')),
                ('elevator_mgrtel', models.CharField(blank=True, max_length=32, null=True, verbose_name='安全员电话')),
                ('elevator_oper', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作员')),
                ('elevator_opertel', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作员电话')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_ElevatorHisData',
            },
        ),
    ]
