# Generated by Django 2.2 on 2019-12-10 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devinterfacesrv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='envinterfacesrv',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FCommandType', models.IntegerField(blank=True, default=2, null=True, verbose_name='命令类型')),
                ('FDeviceId', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备编号')),
                ('FTimestamp', models.IntegerField(blank=True, null=True, verbose_name='原始时间戳')),
                ('FSPM', models.FloatField(blank=True, null=True, verbose_name='SPM粉尘数据')),
                ('FPM25', models.FloatField(blank=True, null=True, verbose_name='PM2.5数据')),
                ('FPM10', models.FloatField(blank=True, null=True, verbose_name='PM10数据')),
                ('FTYPE', models.IntegerField(blank=True, null=True, verbose_name='数据类型')),
                ('FWIND_SPEED', models.FloatField(blank=True, null=True, verbose_name='风速')),
                ('FWIND_DIRECT', models.FloatField(blank=True, null=True, verbose_name='风向度数')),
                ('FWIND_DIRECT_STR', models.CharField(blank=True, max_length=32, null=True, verbose_name='风向文字')),
                ('FTemperature', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('FHumidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('FNoise', models.FloatField(blank=True, null=True, verbose_name='噪音等效值')),
                ('FNoiseMax', models.FloatField(blank=True, null=True, verbose_name='噪音峰值')),
                ('FLongitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('FLatitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('FPressure', models.IntegerField(blank=True, null=True, verbose_name='大气压值')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_EnvdetectionHisData',
            },
        ),
    ]
