# Generated by Django 2.1.4 on 2019-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterfacesrv', '0002_envinterfacesrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='envinterfacesrv',
            name='FSRCTimestamp',
            field=models.IntegerField(blank=True, null=True, verbose_name='原始时间戳'),
        ),
        migrations.AlterField(
            model_name='envinterfacesrv',
            name='FTimestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='获取时间'),
        ),
    ]
