# Generated by Django 2.2 on 2019-12-19 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devinterfacesrv', '0003_auto_20191212_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='interfacesrvdata',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FCallSigCode', models.CharField(blank=True, max_length=32, null=True, verbose_name='调用特征码')),
                ('FTag', models.CharField(blank=True, max_length=20, null=True, verbose_name='标签')),
                ('FValue', models.CharField(blank=True, max_length=20, null=True, verbose_name='值')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_InterfaceSrvData',
            },
        ),
    ]
