# Generated by Django 2.1.4 on 2020-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterfacesrv', '0005_auto_20191220_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='envinterfacesrv',
            name='FTSP',
            field=models.FloatField(blank=True, null=True, verbose_name='TSP悬浮颗粒数据'),
        ),
    ]
