# Generated by Django 2.1.4 on 2020-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinterfacesrv', '0006_envinterfacesrv_ftsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinterfacesrv',
            name='FPressure',
            field=models.FloatField(blank=True, null=True, verbose_name='大气压值'),
        ),
    ]
