# Generated by Django 2.1.4 on 2020-05-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devinterfacesrv', '0007_auto_20200511_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envinterfacesrv',
            options={'ordering': ['-CREATED_TIME']},
        ),
    ]
