# Generated by Django 2.1.4 on 2020-05-31 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filefolder', '0002_auto_20200531_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfiles',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FFolderID', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属文件夹ID')),
                ('FFile', models.ImageField(blank=True, default='', null=True, upload_to='prjfile/', verbose_name='项目文件')),
                ('FFileType', models.CharField(blank=True, max_length=32, null=True, verbose_name='文件类型')),
                ('FFileDesc', models.CharField(blank=True, max_length=32, null=True, verbose_name='文件描述')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_UploadFiles',
            },
        ),
    ]
