# Generated by Django 2.1.4 on 2020-06-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filefolder', '0003_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='FUnionBimModel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='关联模型'),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='FUploader',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上传人员'),
        ),
    ]
