# Generated by Django 2.2 on 2019-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkey', '0002_auto_20191219_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkey',
            name='FAppCreateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='app创建时间'),
        ),
    ]
