# Generated by Django 2.1.4 on 2020-01-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkey', '0003_appkey_fappcreatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkey',
            name='CREATED_PRJ',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目'),
        ),
    ]
