# Generated by Django 2.1.4 on 2020-06-22 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teamworker',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FTeamWorkerTypeID', models.CharField(blank=True, max_length=32, null=True, verbose_name='协作类型')),
                ('FTitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('FDeadLine', models.DateField(blank=True, null=True, verbose_name='完成期限')),
                ('FLevel', models.CharField(blank=True, max_length=32, null=True, verbose_name='优先级')),
                ('FTag', models.CharField(blank=True, max_length=100, null=True, verbose_name='标识')),
                ('FBimModel', models.CharField(blank=True, max_length=200, null=True, verbose_name='关联BIM')),
                ('FPic', models.ImageField(blank=True, default='', null=True, upload_to='twpic/', verbose_name='协同图片')),
                ('FRecord', models.ImageField(blank=True, default='', null=True, upload_to='twrecord/', verbose_name='录音')),
                ('FStakeholder', models.CharField(blank=True, max_length=1000, null=True, verbose_name='干系人')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_TeamWorkerInfo',
            },
        ),
    ]
