# Generated by Django 2.1.4 on 2020-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamworker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamworker',
            name='FClassifyTag',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '待整改'), (1, '进行中'), (2, '已完成'), (3, '已过期')], default=0, null=True, verbose_name='分类标记'),
        ),
    ]
