# Generated by Django 2.2 on 2020-07-06 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teamworker', '0002_teamworker_fclassifytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamworkreply',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FTeamWorkerID', models.CharField(blank=True, max_length=32, null=True, verbose_name='协同ID')),
                ('FReply', models.CharField(blank=True, max_length=1000, null=True, verbose_name='回复内容')),
                ('FPic', models.ImageField(blank=True, default='', null=True, upload_to='twpic/', verbose_name='协同图片')),
                ('FRecord', models.ImageField(blank=True, default='', null=True, upload_to='twrecord/', verbose_name='录音')),
                ('FStakeholder', models.CharField(blank=True, max_length=1000, null=True, verbose_name='@干系人')),
                ('FReadTag', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '未读'), (1, '已读')], default=0, null=True, verbose_name='阅读标记')),
                ('FReplyPerson', models.CharField(blank=True, max_length=32, null=True, verbose_name='回复人')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_TeamWorkReply',
            },
        ),
    ]
