# Generated by Django 2.2 on 2020-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamworker', '0004_teamworker_fapprovememo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamworker',
            name='FApproveDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
    ]
