# Generated by Django 2.1.4 on 2019-08-03 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elecalarm',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FElecFenceID', models.CharField(blank=True, max_length=32, null=True, verbose_name='围栏ID')),
                ('FPlate', models.CharField(blank=True, max_length=32, null=True, verbose_name='报警对象')),
                ('FTriggerType', models.IntegerField(blank=True, choices=[(0, '进入围栏'), (1, '离开围栏')], null=True, verbose_name='触发动作')),
                ('FTriggerlong', models.FloatField(blank=True, null=True, verbose_name='触发坐标经度')),
                ('FTriggerlat', models.FloatField(blank=True, null=True, verbose_name='触发坐标纬度')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_ElecAlarm',
            },
        ),
    ]
