# Generated by Django 2.1.4 on 2019-07-06 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('FPrjID', models.CharField(max_length=32, verbose_name='项目编码')),
                ('FPrjname', models.CharField(max_length=128, verbose_name='项目名称')),
                ('FShortname', models.CharField(blank=True, max_length=128, null=True, verbose_name='项目简称')),
                ('FPrjtypeID', models.CharField(max_length=32, verbose_name='工程类别')),
                ('FPrjuseID', models.CharField(max_length=32, verbose_name='工程用途')),
                ('FPrjstate', models.IntegerField(choices=[(0, '立项'), (1, '在建'), (2, '完工')], default=0, verbose_name='工程状态')),
                ('FStructypeID', models.CharField(max_length=32, verbose_name='结构类型')),
                ('FPrjcost', models.FloatField(blank=True, default=0.0, null=True, verbose_name='工程造价')),
                ('FArea', models.FloatField(blank=True, default=0.0, null=True, verbose_name='建筑面积')),
                ('FAddress', models.CharField(blank=True, max_length=128, null=True, verbose_name='项目地址')),
                ('FLong', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('FLat', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('FSigDate', models.DateField(blank=True, null=True, verbose_name='合同签订日期')),
                ('FSigbeginDate', models.DateField(blank=True, null=True, verbose_name='合同起始日期')),
                ('FSigendDate', models.DateField(blank=True, null=True, verbose_name='合同截止日期')),
                ('FBeginDate', models.DateField(blank=True, null=True, verbose_name='实际起始工期')),
                ('FEndDate', models.DateField(blank=True, null=True, verbose_name='实际截止日期')),
                ('FPrjmanager', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目经理')),
                ('FPrjmanagertel', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目经理电话')),
                ('FWinOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='中标单位')),
                ('FWinAtten', models.CharField(blank=True, max_length=32, null=True, verbose_name='中标单位联系人')),
                ('FWinAttenTel', models.CharField(blank=True, max_length=32, null=True, verbose_name='中标单位联系人电话')),
                ('FBuildOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='建设单位')),
                ('FBuildAtten', models.CharField(blank=True, max_length=32, null=True, verbose_name='建设单位联系人')),
                ('FBuildAttenTel', models.CharField(blank=True, max_length=32, null=True, verbose_name='建设单位联系人电话')),
                ('FDesignOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='设计单位')),
                ('FDesignAtten', models.CharField(blank=True, max_length=32, null=True, verbose_name='设计单位联系人')),
                ('FDesignAttenTel', models.CharField(blank=True, max_length=32, null=True, verbose_name='设计单位联系人电话')),
                ('FSuperviseOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='监理单位')),
                ('FSuperviseAtten', models.CharField(blank=True, max_length=32, null=True, verbose_name='监理单位联系人')),
                ('FSuperviseAttenTel', models.CharField(blank=True, max_length=32, null=True, verbose_name='监理单位联系人电话')),
                ('FUserOrgID', models.CharField(blank=True, max_length=32, null=True, verbose_name='业主单位')),
                ('FUserAtten', models.CharField(blank=True, max_length=32, null=True, verbose_name='业主单位联系人')),
                ('FUserAttenTel', models.CharField(blank=True, max_length=32, null=True, verbose_name='业务单位联系人电话')),
                ('FPrjdesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='工程概况')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_Project',
            },
        ),
    ]
