# Generated by Django 2.2 on 2019-07-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='FManageORG',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='管理组织'),
        ),
    ]
