# Generated by Django 2.2 on 2019-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_fmanageorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='FPrjstate',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工程状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='FPrjtypeID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工程类别'),
        ),
        migrations.AlterField(
            model_name='project',
            name='FPrjuseID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工程用途'),
        ),
        migrations.AlterField(
            model_name='project',
            name='FStructypeID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='结构类型'),
        ),
    ]
