# Generated by Django 2.1.4 on 2020-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200304_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='FAffDept',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='所属科室'),
        ),
    ]
