# Generated by Django 2.1.4 on 2020-03-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200323_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='FcontractorCorpCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='总承包单位统一社会信用代码'),
        ),
        migrations.AddField(
            model_name='project',
            name='FcontractorCorpName',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='总承包单位名称'),
        ),
    ]
