# Generated by Django 2.1.4 on 2020-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_fbuilderlicenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='FConsultAtten',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='咨询单位联系人'),
        ),
        migrations.AddField(
            model_name='project',
            name='FConsultAttenTel',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='咨询单位联系人电话'),
        ),
        migrations.AddField(
            model_name='project',
            name='FConsultOrgID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='咨询单位'),
        ),
    ]
