# Generated by Django 2.1.4 on 2019-08-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0002_goodstype_fdesc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'ordering': ['FPID']},
        ),
    ]
