# Generated by Django 2.1.4 on 2020-03-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodstype', '0003_auto_20190806_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='FStatus',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
