# Generated by Django 2.1.4 on 2019-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmenu',
            name='FMenuPosition',
            field=models.IntegerField(blank=True, choices=[(0, None), (1, '顶部'), (2, '侧边')], default=0, null=True, verbose_name='菜单位置'),
        ),
    ]
