# Generated by Django 2.1.4 on 2019-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0002_busmenu_fmenuposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmenu',
            name='FStatus',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
