# Generated by Django 2.1.4 on 2019-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0003_busmenu_fstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmenu',
            name='FFoldState',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '折叠'), (1, '展开')], default=0, null=True, verbose_name='菜单折叠'),
        ),
        migrations.AlterField(
            model_name='busmenu',
            name='FMenuPosition',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '顶部'), (1, '侧边')], default=0, null=True, verbose_name='菜单位置'),
        ),
    ]
