# Generated by Django 2.1.4 on 2019-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0004_auto_20191114_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmenu',
            name='FFormState',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '嵌入式'), (1, '新窗口')], default=0, null=True, verbose_name='打开模式'),
        ),
    ]
