# Generated by Django 2.1.4 on 2019-11-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0005_busmenu_fformstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmenu',
            name='FMenuPosition',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '顶部'), (1, '侧边'), (2, '数据中心')], default=0, null=True, verbose_name='菜单位置'),
        ),
    ]
