# Generated by Django 2.1.4 on 2020-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0006_auto_20191130_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmenu',
            name='FFormState',
            field=models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '嵌入式'), (1, '新窗口'), (2, '原窗口全屏')], default=0, null=True, verbose_name='打开模式'),
        ),
    ]
