# Generated by Django 2.1.4 on 2020-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0007_auto_20200303_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmenu',
            name='FGroupID',
            field=models.IntegerField(blank=True, null=True, verbose_name='菜单组'),
        ),
    ]
