# Generated by Django 2.2 on 2020-07-22 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0008_busmenu_fgroupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='authmenu',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FUserGroupID', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户组FID')),
                ('FBusMenuID', models.CharField(blank=True, max_length=5000, null=True, verbose_name='菜单ID')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_AuthMenu',
            },
        ),
    ]
