# Generated by Django 2.2 on 2020-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmenu', '0009_authmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmenu',
            name='FBusMenuID',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单ID'),
        ),
    ]
