# Generated by Django 2.1.4 on 2019-09-11 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FName', models.CharField(blank=True, max_length=32, null=True, verbose_name='访客姓名')),
                ('FSex', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('FVisitorIDcard', models.CharField(blank=True, max_length=18, null=True, verbose_name='访客身份证')),
                ('FValidDate', models.DateField(blank=True, null=True, verbose_name='有效日期')),
                ('FRefundDate', models.DateField(blank=True, null=True, verbose_name='退卡日期')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'T_Visitor',
            },
        ),
    ]
