# Generated by Django 2.1.4 on 2019-09-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='CREATED_BY',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='CREATED_ORG',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='CREATED_PRJ',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='CREATED_TIME',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='FStatus',
            field=models.IntegerField(choices=[(None, '请选择数据'), (0, '登记'), (1, '退场'), (2, '禁用')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='UPDATED_BY',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='UPDATED_TIME',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
