# Generated by Django 2.1.4 on 2019-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20190911_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='FOriginName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属组织'),
        ),
    ]
