# Generated by Django 2.1.4 on 2019-07-29 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='envdatalog',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FDevID', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备ID')),
                ('FNodename', models.CharField(blank=True, max_length=32, null=True, verbose_name='节点名称')),
                ('FMonitoritem1', models.CharField(blank=True, max_length=32, null=True, verbose_name='监测内容(一)')),
                ('FMonitorvalue1', models.CharField(blank=True, max_length=32, null=True, verbose_name='监测值(一)')),
                ('FMonitoritem2', models.CharField(blank=True, max_length=32, null=True, verbose_name='监测内容(二)')),
                ('FMonitorvalue2', models.CharField(blank=True, max_length=32, null=True, verbose_name='监测值(二)')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_EnvDataLog',
            },
        ),
    ]
