# Generated by Django 2.1.4 on 2019-07-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatalertlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatalertlog',
            name='FRuleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatrule.hatrule', verbose_name='规则ID'),
        ),
    ]
