# Generated by Django 2.1.4 on 2019-07-19 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personauth',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FPersonID', models.CharField(blank=True, max_length=32, null=True, verbose_name='人员ID')),
                ('FAreaID', models.CharField(blank=True, max_length=32, null=True, verbose_name='区域ID')),
                ('FAuthtype', models.IntegerField(choices=[(0, '正式授权'), (1, '临时授权')], default=0, verbose_name='授权类型')),
                ('FVisitor', models.CharField(blank=True, max_length=32, null=True, verbose_name='访客姓名')),
                ('FVisitorIDcard', models.CharField(blank=True, max_length=18, null=True, verbose_name='访客身份证')),
                ('FValidDate', models.DateField(blank=True, null=True, verbose_name='有效日期')),
                ('FRefundDate', models.DateField(blank=True, null=True, verbose_name='退卡日期')),
                ('FICcardno', models.CharField(blank=True, max_length=32, null=True, verbose_name='临时通行卡号')),
                ('FDesc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('FStatus', models.IntegerField(choices=[(None, '请选择数据'), (0, '生效'), (1, '失效'), (2, '退卡')], default=0, verbose_name='状态')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_PersonPassAuth',
            },
        ),
    ]
