# Generated by Django 2.1.4 on 2020-02-17 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prjprocess',
            fields=[
                ('FID', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('FProcessName', models.CharField(blank=True, max_length=50, null=True, verbose_name='阶段名称')),
                ('FScheduleTime', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('FPlanStatus', models.IntegerField(blank=True, choices=[(None, '请选择数据'), (0, '计划中'), (1, '已完成')], default=0, null=True, verbose_name='阶段状态')),
                ('FCompleteTime', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('FStatus', models.BooleanField(default=True, verbose_name='状态')),
                ('CREATED_PRJ', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属项目')),
                ('CREATED_ORG', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建组织')),
                ('CREATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('CREATED_TIME', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('UPDATED_BY', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人')),
                ('UPDATED_TIME', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'T_PrjProcess',
            },
        ),
    ]
