# Generated by Django 2.1.4 on 2020-02-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjprocess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prjprocess',
            name='FDesc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
    ]
