# Generated by Django 2.1.4 on 2020-03-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prjprocess', '0002_prjprocess_fdesc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prjprocess',
            options={'ordering': ['FScheduleTime']},
        ),
    ]
