# Generated by Django 2.2 on 2020-07-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ismsapi', '0002_tasklist_ftasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='FScope',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='任务范围'),
        ),
    ]
