# Generated by Django 2.1.4 on 2019-09-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unit',
            new_name='usergroup',
        ),
    ]
